language: generic

addons:
  firefox: "latest"

python:
  - "2.7"

matrix:
  include:
    - os: linux
      env:
        - TARGET=x86_64-unknown-linux-musl
        - NAME=linux64
        - EXT=tar.gz
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
          - musl-tools
          - libbz2-dev

before_install:
  - git clone https://github.com/mozilla/geckodriver.git
  - ln -s geckodriver/src src
  - ln -s geckodriver/Cargo.toml Cargo.toml
  - ln -s geckodriver/Cargo.lock Cargo.lock
  - export PATH="$PATH:$HOME/.cargo/bin"
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable
  - rustc -V
  - cargo -V
  - wget -O - https://raw.githubusercontent.com/mozilla/geckodriver/master/ci.sh | bash

install:
  - travis_retry pip install -U pip wheel setuptools
#  - travis_retry pip install python-coveralls codecov
  - travis_retry pip install -e . -r requirements.txt
  - pip uninstall -y tierra_qa
  - python setup.py develop
  - python setup.py dev

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - py.test --runslow --tb=native --driver Firefox --credentials="Administrator;admin;admin"
