language: generic

addons:
  firefox: "latest"

python:
  - "2.7"

matrix:
  include:
    - os: linux
      env:
        - TARGET=x86_64-unknown-linux-musl
        - NAME=linux64
        - EXT=tar.gz
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
          - musl-tools
          - libbz2-dev

before_install:
  - mkdir src
  - wget  -O - https://raw.githubusercontent.com/mozilla/geckodriver/master/src/main.rs > src/main.rs
  - wget  -O - https://raw.githubusercontent.com/mozilla/geckodriver/master/src/marionette.rs > src/marionette.rs
  - wget https://raw.githubusercontent.com/mozilla/geckodriver/master/Cargo.toml
  - wget https://raw.githubusercontent.com/mozilla/geckodriver/master/Cargo.lock
  - export PATH="$PATH:$HOME/.cargo/bin"
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable
  - rustc -V
  - cargo -V
  - wget -O - https://raw.githubusercontent.com/mozilla/geckodriver/master/ci.sh | bash

install:
  - travis_retry pip install -U pip wheel setuptools
#  - travis_retry pip install python-coveralls codecov
  - travis_retry pip install -e . -r requirements.txt
  - pip uninstall -y tierra_qa
  - python setup.py develop
  - python setup.py dev

script:
  - py.test --runslow --tb=native --driver Firefox --credentials="Administrator;admin;admin"
