language: python
sudo: false
addons:
  firefox: "48.0"
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
python:
  - "2.7"
  - "3.5"
before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable
  - rustc -V
  - cargo -V
  - wget -O - https://raw.githubusercontent.com/mozilla/geckodriver/master/ci.sh | bash
install:
  - travis_retry pip install -U pip wheel setuptools
#  - travis_retry pip install python-coveralls codecov
  - travis_retry pip install -e . -r requirements.txt
  - pip uninstall -y tierra_qa
  - python setup.py develop
  - python setup.py dev
script:
  - py.test --runslow --tb=native --driver Firefox --credentials="Administrator;admin;admin"
#after_success:
#  - coveralls
#  - codecov
