language: python
sudo: required 

addons:
  firefox: "latest"

python:
  - "2.7"
  - "3.5"

env:
  - TOXENV=phantomjs
  - TOXENV=firefox
  - TOXENV=chrome
  - TOXENV=docs
  - TOXENV=linkcheck
  - TOXENV=codecov

matrix:
  allow_failures:
  - env: TOXENV=firefox
  - env: TOXENV=chrome
  - python: "3.5"
  exclude:
  - python: "3.5"
    env: TOXENV=docs
  - python: "3.5"
    env: TOXENV=linkcheck

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
  
install:
  - travis_retry pip install -U pip wheel setuptools
  - travis_retry pip install -r requirements.txt
  - python setup.py develop

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - export PATH="$PATH:`pwd`/bin"
  - ./scripts/setup_travis.sh
  - tox -e ${TOXENV}

after_success:
  - bash <(curl -s https://codecov.io/bash)
