language: python
sudo: false

addons:
  firefox: "latest"

python:
  - "2.7"
  - "3.5"

env:
  - DRIVER=phantomjs
  - DRIVER=firefox
  - DRIVER=chrome

matrix:
  allow_failures:
    - env: DRIVER=firefox
    - env: DRIVER=chrome
    - python: "3.5"
  
install:
  - travis_retry pip install -U pip wheel setuptools
  - travis_retry pip install -r requirements.txt
  - python setup.py develop

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - export PATH="$PATH:`pwd`/bin"
  - ./scripts/setup_travis.sh
  - tox -e ${DRIVER}
