language: python
sudo: false

python:
  - "2.7"
#  - "3.5"

env:
  - DRIVER=phantomjs
  - DRIVER=firefox
#  - DRIVER=chrome
  
cache:
  directories:
    # /home/travis/.cache/pip/wheels is the normal pip cache folder
    - $HOME/.cache/pip
    - .tox

before_install:
  - ./scripts/setup_travis.sh

install:
  - travis_retry pip install -U pip wheel setuptools
  - travis_retry pip install -r requirements.txt
  - python setup.py develop

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - tox -e ${DRIVER}
  # - py.test --runslow --tb=native --splinter-webdriver=phantomjs --credentials="Administrator;admin;admin"
